server:
  port: 8080

spring:
  application:
    name: clinica
  datasource:
    url: jdbc:postgresql://localhost:5432/clinica_db
    username: clinica
    password: clinica123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  jwt:
    secret: "uE1qUxiTg2D2W0AHG+hEc8JuR2UYsS93+bFC/YqFcF0="
    expiration-ms: 86400000
  cors:
    allowed-origin: "http://localhost:4200"
  mail:
    from: "no-reply@clinica.local"
    enabled: false
  dni-api:
    url: "https://miapi.cloud/v1/dni"
    token: ""

logging:
  level:
    org.springframework.security: INFO
    com.web.clinica: DEBUG
